# SQL Server数据库配置
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://119.45.239.3:1433;DatabaseName=mingpin;encrypt=false
    username: sa
    password: MingPin2024
  data:
    redis:
      host: 119.45.239.3
      port: 6379
      password:
      database: 0
  application:
    name: springfox-swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: classpath:oss.properties


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  # ?????????
      logic-delete-field: deleted  # ????????
      logic-not-delete-value: 0  # ?????
      logic-delete-value: 1  # ?????
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ?? SQL ??????????

aliyun:
  oss:
    endpoint: ${server_endpoint}
    accessKeyId: ${access_key_id}
    accessKeySecret: ${access_key_secret}
    bucketName: ${bucket_name}

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    org.mybatis : DEBUG

server:
  port: 8080
  servlet:
    context-path:

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}
